---
title: "Introdução ao R para Ciências Econômicas"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Resumo 

Este repositório contém os materiais utilizados na apresentação de introdução ao R para estudantes de Ciências Econômicas da Universidade Federal do Delta do Parnaíba (UFDPar), realizado durante os minicursos "Introdução ao R" e "Práticas no R" nos dias 5 e 6 de julho de 2024, durante o evento *Data Economics* pelo Centro Acadêmico de Economia.

Os minicursos abordam os seguintes tópicos:

- Introdução geral ao R e RStudio
- Estruturas de dados: vetores, data frames e listas
- Estruturas de controle: condicionais e loops, introduzidos através de funções
- Análise estatística básica
- Visualização de dados


## Acesso aos Slides

Os slides do curso podem ser acessados [aqui](https://drewmelo.github.io/introducao-R/#/title-slide).

## Como Clonar Este Repositório

Para clonar este repositório localmente, utilize o seguinte comando Git:

```sh
   git clone https://github.com/drewmelo/introducao-R.git
```
